### DISCUSSION TITLE
Deploy Structurizr Lite on Kubernetes

### DISCUSSION THREAD

**Discussion by njanet-vl** [structurizr/lite#159] [Q&A] [answered]
Hello,

First, I would like to say that Structurizr is a great tool!

I work on a POC to use Structurizr Lite on my company Kubernetes cluster to share architecture diagrams among my R&D team.

I built a Docker image (from `structurizr/lite::2024.07.02`) copying all my DSL files. When run locally this image works perfectly.

K8S deployment works well (using kubectl) and https://my-cluster/structurizr/health responds OK.

However I was not able to make the UI work properly from my browser. Although HTML files and other static resources load well, I get a 400 error code when calling the API:

`[GET] https://my-cluster/structurizr/api/workspace/1?_=1724938170486`
returns
`{"success":false,"message":"Authorization header doesn't match"}`

Do you have any idea of what is causing this issue ? Is it realistic to do such deployment ?

I suspect an issue with the path computation in the hash based authentication but I am not sure.

Here is my structurizr.properties file

`
structurizr.url=https://my-cluster/structurizr
structurizr.editable=false
`

Here is my K8S ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: structurizr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /structurizr
spec:
  ingressClassName: nginx
  rules:
    - host: my-cluster
      http:
        paths:
          - backend:
              service:
                name: structurizr
                port:
                  number: 8080
            pathType: ImplementationSpecific
            path: /structurizr(/|$)(.*)
```

Thanks for your help

Nicolas
