### ISSUE TITLE
Documentation suggestion for Lite

### ISSUE THREAD

**Issue by Martin-Narvar** [structurizr/lite#1]
I ran Structurizr Lite using Docker compose. I share my docker-compose.yaml here in case anyone else finds it useful.

```yaml
version: '3'
services:
  structurizr:
    container_name: system-architecture-structurizr
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - "./src:/usr/local/structurizr:rw"
```
