### ISSUE TITLE
400 on default view, no logs

### ISSUE THREAD

**Issue by Coldknife2** [structurizr/lite#158]
### Expected

Default view

### Actual

400
![image](https://github.com/user-attachments/assets/45b211c3-3100-400d-8d80-6e6a5eb08d84)

### Steps to reproduce

docker pull structurizr/lite
docker run -it --rm -p 8080:8080 -v .:/usr/local/structurizr structurizr/lite

then open web browser on localhost:8080

### Version/build information

Structurizr Lite
- build: 2024.07.02 (2024-07-02T12:09:42Z)
- structurizr-java: v2.2.0
 - structurizr-dsl: v2.2.0
- structurizr-import: v2.2.0
-  structurizr-graphviz: v2.2.0

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
`docker run -it --rm -p 8080:8080 -v .:/usr/local/structurizr structurizr/lite` works as expected for me.

Assuming it exists, there could be a problem with your `workspace.dsl` file.

**Comment by Coldknife2** [comment]
Real strange, I tried to delete the workspace.dsl when I first reported the issue. I just deleted again the one that get generated by default, it now works.
Guess I'll close the issue, thanks for looking.

**Comment by mikhail-rush** [comment]
I started getting the same issue last week. Starting from scratch with a [default DSL](https://structurizr.com/dsl) in `workspace.dsl` does not fix. 

My environment:

- OS: Mac OS Sequoia 15.1 
- Docker version 27.3.1, build ce12230
- structurizr/lite image: sha256:df213187abf9a31090e887c08f7641077ba4dcd41c9f64ecb7d1fc11a28c73cb

`docker-compose.yml`:

```yaml
version: '3.5'
services:
  structurizr:
    image: structurizr/lite:latest
    volumes: 
        - ./:/usr/local/structurizr
    environment:
      STRUCTURIZR_WORKSPACE_PATH: .
    ports: 
        - "8080:8080"
```
